from refiners.fluxion.match_state_dict import match_state_dict


def test_match_state_dict_simple() -> None:
    source = {"DropoutAdapter.Linear.weight": "foo", "DropoutAdapter.Linear.bias": "bar"}
    target = {"Linear.weight": "init", "Linear.bias": "init"}

    out = match_state_dict(source, target)
    assert out == {"Linear.weight": "foo", "Linear.bias": "bar"}


def test_match_state_dict_simple_reverse() -> None:
    source = {"Linear.weight": "foo", "Linear.bias": "bar"}
    target = {"DropoutAdapter.Linear.weight": "init", "DropoutAdapter.Linear.bias": "init"}

    out = match_state_dict(source, target)
    assert out == {"DropoutAdapter.Linear.weight": "foo", "DropoutAdapter.Linear.bias": "bar"}


def test_match_state_dict_asym_dropout() -> None:
    source = {"DropoutAdapter.Linear.weight": "foo", "Linear.weight": "bar"}
    target = {"Linear_1.weight": "init", "Linear_2.weight": "init"}

    out = match_state_dict(source, target)
    assert out == {"Linear_1.weight": "foo", "Linear_2.weight": "bar"}


def test_match_state_dict_asym_dropout_reverse() -> None:
    source = {"Linear_1.weight": "foo", "Linear_2.weight": "bar"}
    target = {"DropoutAdapter.Linear.weight": "init", "Linear.weight": "init"}

    out = match_state_dict(source, target)
    assert out == {"DropoutAdapter.Linear.weight": "foo", "Linear.weight": "bar"}


def test_match_state_dict_chain() -> None:
    source = {
        "Chain.Chain_1.Linear": "foo1",
        "Chain.Chain_1.Conv": "bar1",
        "Chain.Chain_2.Linear": "foo2",
        "Chain.Chain_2.Conv": "bar2",
    }

    target = {"Chain.Linear_1": "init", "Chain.Conv_1": "init", "Chain.Linear_2": "init", "Chain.Conv_2": "init"}

    out = match_state_dict(source, target)
    assert out == {"Chain.Linear_1": "foo1", "Chain.Conv_1": "bar1", "Chain.Linear_2": "foo2", "Chain.Conv_2": "bar2"}


def test_match_state_dict_chain_reverse() -> None:
    source = {"Chain.Linear_1": "foo1", "Chain.Conv_1": "bar1", "Chain.Linear_2": "foo2", "Chain.Conv_2": "bar2"}

    target = {
        "Chain.Chain_1.Linear": "init",
        "Chain.Chain_1.Conv": "init",
        "Chain.Chain_2.Linear": "init",
        "Chain.Chain_2.Conv": "init",
    }

    out = match_state_dict(source, target)
    assert out == {
        "Chain.Chain_1.Linear": "foo1",
        "Chain.Chain_1.Conv": "bar1",
        "Chain.Chain_2.Linear": "foo2",
        "Chain.Chain_2.Conv": "bar2",
    }


TARGET = {
 "Chain_1.Encoder.Conv3d.weight": "value",
 "Chain_1.Encoder.Conv3d.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Downsample3d.Conv3d.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_1.Downsample3d.Conv3d.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Downsample3d.Conv3d.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_2.Downsample3d.Conv3d.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Downsample3d.Conv3d.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_3.Downsample3d.Conv3d.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Downsample3d.Conv3d.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_4.Downsample3d.Conv3d.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Downsample3d.Conv3d.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_5.Downsample3d.Conv3d.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.GroupNorm.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.GroupNorm.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.Linear_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.Linear_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.Linear_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.Linear_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.Linear_3.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.Linear_3.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Linear.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Linear.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_1.Encoder.Chain_2.GroupNorm.weight": "value",
 "Chain_1.Encoder.Chain_2.GroupNorm.bias": "value",
 "Chain_1.Encoder.Chain_2.Conv3d.weight": "value",
 "Chain_1.Encoder.Chain_2.Conv3d.bias": "value",
 "Chain_1.Encoder.Chain_3.Conv3d.weight": "value",
 "Chain_1.Encoder.Chain_3.Conv3d.bias": "value",
 "Chain_2.Decoder.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.GroupNorm.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.GroupNorm.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.Linear_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.Linear_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.Linear_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.Linear_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.Linear_3.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.Linear_3.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Linear.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Linear.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Upsample3d.Conv3d.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_2.Upsample3d.Conv3d.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Upsample3d.Conv3d.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_3.Upsample3d.Conv3d.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Upsample3d.Conv3d.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_4.Upsample3d.Conv3d.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Upsample3d.Conv3d.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_5.Upsample3d.Conv3d.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.GroupNorm_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.GroupNorm_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.Conv3d_1.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.Conv3d_1.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.GroupNorm_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.GroupNorm_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.Conv3d_2.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.Conv3d_2.bias": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Upsample3d.Conv3d.weight": "value",
 "Chain_2.Decoder.Chain_1.Chain_6.Upsample3d.Conv3d.bias": "value",
 "Chain_2.Decoder.Chain_2.GroupNorm.weight": "value",
 "Chain_2.Decoder.Chain_2.GroupNorm.bias": "value",
 "Chain_2.Decoder.Chain_2.Conv3d.weight": "value",
 "Chain_2.Decoder.Chain_2.Conv3d.bias": "value",
}

SOURCE = {
 "Chain_1.Encoder.Chain_1.Chain_1.Downsample3d.Conv3d.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Downsample3d.Conv3d.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Downsample3d.Conv3d.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Downsample3d.Conv3d.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Downsample3d.Conv3d.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Downsample3d.Conv3d.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Downsample3d.Conv3d.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Downsample3d.Conv3d.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Downsample3d.Conv3d.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Downsample3d.Conv3d.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.GroupNorm.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.GroupNorm.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.DropoutAdapter_1.DropoutAdapter.Linear.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.DropoutAdapter_1.DropoutAdapter.Linear.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.DropoutAdapter_2.DropoutAdapter.Linear.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.DropoutAdapter_2.DropoutAdapter.Linear.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.DropoutAdapter_3.DropoutAdapter.Linear.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.Distribute.DropoutAdapter_3.DropoutAdapter.Linear.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.DropoutAdapter.DropoutAdapter.Linear.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Residual.SelfAttention3d.DropoutAdapter.DropoutAdapter.Linear.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_1.Encoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_1.Encoder.Chain_2.Conv3d.bias": "value1",
 "Chain_1.Encoder.Chain_2.Conv3d.weight": "value1",
 "Chain_1.Encoder.Chain_2.GroupNorm.bias": "value1",
 "Chain_1.Encoder.Chain_2.GroupNorm.weight": "value1",
 "Chain_1.Encoder.Chain_3.Conv3d.bias": "value1",
 "Chain_1.Encoder.Chain_3.Conv3d.weight": "value1",
 "Chain_1.Encoder.Conv3d.bias": "value1",
 "Chain_1.Encoder.Conv3d.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.GroupNorm.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.GroupNorm.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.DropoutAdapter_1.DropoutAdapter.Linear.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.DropoutAdapter_1.DropoutAdapter.Linear.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.DropoutAdapter_2.DropoutAdapter.Linear.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.DropoutAdapter_2.DropoutAdapter.Linear.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.DropoutAdapter_3.DropoutAdapter.Linear.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.Distribute.DropoutAdapter_3.DropoutAdapter.Linear.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.DropoutAdapter.DropoutAdapter.Linear.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Residual.SelfAttention3d.DropoutAdapter.DropoutAdapter.Linear.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_1.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Resnet_3.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Upsample3d.Conv3d.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_2.Upsample3d.Conv3d.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Resnet_3.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Upsample3d.Conv3d.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_3.Upsample3d.Conv3d.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Resnet_3.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Upsample3d.Conv3d.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_4.Upsample3d.Conv3d.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Resnet_3.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Upsample3d.Conv3d.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_5.Upsample3d.Conv3d.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_1.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_2.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.Conv3d_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.GroupNorm_1.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.GroupNorm_1.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.GroupNorm_2.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Resnet_3.Chain.GroupNorm_2.weight": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Upsample3d.Conv3d.bias": "value1",
 "Chain_2.Decoder.Chain_1.Chain_6.Upsample3d.Conv3d.weight": "value1",
 "Chain_2.Decoder.Chain_2.Conv3d.bias": "value1",
 "Chain_2.Decoder.Chain_2.Conv3d.weight": "value1",
 "Chain_2.Decoder.Chain_2.GroupNorm.bias": "value1",
 "Chain_2.Decoder.Chain_2.GroupNorm.weight": "value1",
 "Chain_2.Decoder.Conv3d_1.bias": "value1",
 "Chain_2.Decoder.Conv3d_1.weight": "value1",
 "Chain_2.Decoder.Conv3d_2.bias": "value1",
 "Chain_2.Decoder.Conv3d_2.weight": "value1"
}


def test_real_life_scenario() -> None:
    assert match_state_dict(SOURCE, TARGET)
